Repository bank-vaults/vault-secrets-reloader, pull requests merged in 2024-02, with the labels that each got.

#124 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/S

#132 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS

#130 chore: update bank-vaults deps
  .licensei.toml
  go.mod
  go.sum
Labels: size/XL
